services:
  app:
    image: snr1s3/flightsasl:latest
    restart: unless-stopped
    ports: ["8000:8000"]
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: FLIGHTSASL
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  postgres:
    image: postgres:16
    restart: unless-stopped
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: FLIGHTSASL
    volumes:
      - flights-postgres-data:/var/lib/postgresql/data
      - ../../src/db/db.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ../../src/db/db_functions.sql:/docker-entrypoint-initdb.d/02_functions.sql
volumes:
  flights-postgres-data: